### ISSUE TITLE
settings module error

### ISSUE THREAD

**Issue by peddollakishore** [dhananjaymehta/FannieMae_LoanForeclosure#1]
in python the settings module is not working, how to resolve that issue.

**Comment by dhananjaymehta** [comment]
@peddollakishore can you provide the error logs

**Comment by peddollakishore** [comment]
Hi @dhananjaymehta Thanks for reply, and bellow is my error.
`import os
import pandas as pd 
import numpy as np
import settings as st
Traceback (most recent call last):

  File "<ipython-input-1-4f7bbb0d07cc>", line 4, in <module>
    import settings as st

ImportError: No module named settings`

**Comment by peddollakishore** [comment]
@dhananjaymehta its working thanks
